name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.1.0"

      - name: Install dependencies
        run: yarn install

      - name: Build TypeScript
        run: yarn build

      - name: Build Docker image
        run: |
          docker build -t {Docker Image Name} .
      
      - name: Tag Docker image
        run: docker tag {Docker Image Name} {Docker Name}/{Docker Image Name}:latest

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: ...

      - name: Install sshpass
        run: ...
      
      - name: Deploy to Server
        env:
          ...
        run: |
          ...